ports:
  - port: 8050
    onOpen: open-preview

tasks:
  - command: |
      curl -k -o miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-py38_4.12.0-Linux-x86_64.sh
      conda create --prefix ./envs python=3.6
      conda activate ./envs
      conda install anaconda-project
      anaconda-project run